### PR TITLE
Redirect all links in pyro.ai/numpyro

### PR DESCRIPTION
**Pull request by fehiepsi**
A follow-up PR of https://github.com/pyro-ppl/numpyro/pull/791. This redirects all old links to tutorials/examples to the new readthedocs site.

Other changes:
+ remove .ipynb_checkpoints files
+ fix numpyro link in Pyro [index file](https://github.com/pyro-ppl/website/pull/9/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R79)

~Blocked until https://github.com/pyro-ppl/numpyro/pull/791 is merged.~

### CODE REVIEW

**Comment by fritzo** [comment]
LGTM, as long as it works :smile:

**Comment by fehiepsi** [comment]
I hope so. Currently, the numpyro PR works: http://num.pyro.ai/en/latest/ :D

**Comment by fehiepsi** [comment]
Let me merge and see if the redirect pattern works. If not, I will revert the merge.

**Comment by fehiepsi** [comment]
I checked several links in the forum and they work as expected. Cheers,

**Pull request merged**
